build:
  image: fracting/msys32
  shell: msys32
  commands:
    - pacman -S --noconfirm mingw-w64-i686-llvm
    - ./configure --prefix=mingw32 --build=mingw32 --host=mingw32 --target=mingw32
    - make
